import React from "react";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy - ChatApp",
  description: "Privacy Policy for ChatApp",
};

const PrivacyPolicy = () => {
  return (
    <div className="container mx-auto p-4">
      <h1 className="text-2xl font-bold mb-4">Privacy Policy</h1>
      <p className="mb-4">Last updated: August 20, 2024</p>

      <p className="mb-4">
        This Privacy Policy describes Our policies and procedures on the
        collection, use, and disclosure of Your information when You use the
        Service and tells You about Your privacy rights and how the law protects
        You.
      </p>
      <p className="mb-4">
        We use Your Personal data to provide and improve the Service. By using
        the Service, You agree to the collection and use of information in
        accordance with this Privacy Policy. This Privacy Policy has been
        created with the help of the Privacy Policy Generator.
      </p>

      <h2 className="text-xl font-semibold mt-4">
        Interpretation and Definitions
      </h2>
      <h3 className="text-lg font-semibold mt-4">Interpretation</h3>
      <p className="mb-4">
        The words of which the initial letter is capitalized have meanings
        defined under the following conditions. The following definitions shall
        have the same meaning regardless of whether they appear in singular or
        in plural.
      </p>

      <h3 className="text-lg font-semibold mt-4">Definitions</h3>
      <p className="mb-4">For the purposes of this Privacy Policy:</p>
      <ul className="list-disc ml-6 mb-4">
        <li>
          <strong>Account</strong> means a unique account created for You to
          access our Service or parts of our Service.
        </li>
        <li>
          <strong>Affiliate</strong> means an entity that controls, is
          controlled by, or is under common control with a party, where
          "control" means ownership of 50% or more of the shares, equity
          interest, or other securities entitled to vote for the election of
          directors or other managing authority.
        </li>
        <li>
          <strong>Company</strong> (referred to as either "the Company", "We",
          "Us", or "Our" in this Agreement) refers to ChatApp.
        </li>
        <li>
          <strong>Cookies</strong> are small files that are placed on Your
          computer, mobile device, or any other device by a website, containing
          the details of Your browsing history on that website among its many
          uses.
        </li>
        <li>
          <strong>Country</strong> refers to: Bangladesh
        </li>
        <li>
          <strong>Device</strong> means any device that can access the Service
          such as a computer, a cellphone, or a digital tablet.
        </li>
        <li>
          <strong>Personal Data</strong> is any information that relates to an
          identified or identifiable individual.
        </li>
        <li>
          <strong>Service</strong> refers to the Website.
        </li>
        <li>
          <strong>Service Provider</strong> means any natural or legal person
          who processes the data on behalf of the Company. It refers to
          third-party companies or individuals employed by the Company to
          facilitate the Service, to provide the Service on behalf of the
          Company, to perform services related to the Service, or to assist the
          Company in analyzing how the Service is used.
        </li>
        <li>
          <strong>Third-party Social Media Service</strong> refers to any
          website or any social network website through which a User can log in
          or create an account to use the Service.
        </li>
        <li>
          <strong>Usage Data</strong> refers to data collected automatically,
          either generated by the use of the Service or from the Service
          infrastructure itself (for example, the duration of a page visit).
        </li>
        <li>
          <strong>Website</strong> refers to ChatApp, accessible from{" "}
          <a
            href="https://sadman-chat-app.vercel.app/"
            className="text-blue-500"
          >
            https://sadman-chat-app.vercel.app/
          </a>
        </li>
        <li>
          <strong>You</strong> means the individual accessing or using the
          Service, or the company, or other legal entity on behalf of which such
          individual is accessing or using the Service, as applicable.
        </li>
      </ul>

      <h2 className="text-xl font-semibold mt-4">
        Collecting and Using Your Personal Data
      </h2>
      <h3 className="text-lg font-semibold mt-4">Types of Data Collected</h3>
      <h4 className="text-md font-semibold mt-4">Personal Data</h4>
      <p className="mb-4">
        While using Our Service, We may ask You to provide Us with certain
        personally identifiable information that can be used to contact or
        identify You. Personally identifiable information may include, but is
        not limited to:
      </p>
      <ul className="list-disc ml-6 mb-4">
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Phone number</li>
      </ul>

      <h4 className="text-md font-semibold mt-4">Usage Data</h4>
      <p className="mb-4">
        Usage Data is collected automatically when using the Service. Usage Data
        may include information such as Your Device's Internet Protocol address
        (e.g. IP address), browser type, browser version, the pages of our
        Service that You visit, the time and date of Your visit, the time spent
        on those pages, unique device identifiers, and other diagnostic data.
      </p>
      <p className="mb-4">
        When You access the Service by or through a mobile device, We may
        collect certain information automatically, including, but not limited
        to, the type of mobile device You use, Your mobile device unique ID, the
        IP address of Your mobile device, Your mobile operating system, the type
        of mobile Internet browser You use, unique device identifiers and other
        diagnostic data.
      </p>
      <p className="mb-4">
        We may also collect information that Your browser sends whenever You
        visit our Service or when You access the Service by or through a mobile
        device.
      </p>

      <h4 className="text-md font-semibold mt-4">
        Information from Third-Party Social Media Services
      </h4>
      <p className="mb-4">
        The Company allows You to create an account and log in to use the
        Service through the following Third-party Social Media Services:
      </p>
      <ul className="list-disc ml-6 mb-4">
        <li>Google</li>
        <li>Facebook</li>
        <li>Instagram</li>
        <li>Twitter</li>
        <li>LinkedIn</li>
      </ul>
      <p className="mb-4">
        If You decide to register through or otherwise grant us access to a
        Third-Party Social Media Service, We may collect Personal data that is
        already associated with Your Third-Party Social Media Service's account,
        such as Your name, Your email address, Your activities or Your contact
        list associated with that account.
      </p>
      <p className="mb-4">
        You may also have the option of sharing additional information with the
        Company through Your Third-Party Social Media Service's account. If You
        choose to provide such information and Personal Data, during
        registration or otherwise, You are giving the Company permission to use,
        share, and store it in a manner consistent with this Privacy Policy.
      </p>

      <h3 className="text-lg font-semibold mt-4">
        Tracking Technologies and Cookies
      </h3>
      <p className="mb-4">
        We use Cookies and similar tracking technologies to track the activity
        on Our Service and store certain information. Tracking technologies used
        are beacons, tags, and scripts to collect and track information and to
        improve and analyze Our Service. The technologies We use may include:
      </p>
      <ul className="list-disc ml-6 mb-4">
        <li>
          <strong>Cookies or Browser Cookies</strong>: A cookie is a small file
          placed on Your Device. You can instruct Your browser to refuse all
          Cookies or to indicate when a Cookie is being sent. However, if You do
          not accept Cookies, You may not be able to use some parts of our
          Service.
        </li>
        <li>
          <strong>Web Beacons</strong>: Certain sections of our Service and our
          emails may contain small electronic files known as web beacons (also
          referred to as clear gifs, pixel tags, and single-pixel gifs) that
          permit the Company, for example, to count users who have visited those
          pages or opened an email and for other related website statistics (for
          example, recording the popularity of a certain section and verifying
          system and server integrity).
        </li>
      </ul>
      <p className="mb-4">
        We use both Session and Persistent Cookies for the following purposes:
      </p>
      <ul className="list-disc ml-6 mb-4">
        <li>
          <strong>Necessary / Essential Cookies</strong>: These Cookies are
          essential to provide You with services available through the Website
          and to enable You to use some of its features.
        </li>
        <li>
          <strong>Cookies Policy / Notice Acceptance Cookies</strong>: These
          Cookies identify if users have accepted the use of cookies on the
          Website.
        </li>
        <li>
          <strong>Functionality Cookies</strong>: These Cookies allow us to
          remember choices You make when You use the Website, such as
          remembering your login details or language preference.
        </li>
      </ul>

      <h2 className="text-xl font-semibold mt-4">Use of Your Personal Data</h2>
      <p className="mb-4">
        The Company may use Personal Data for the following purposes:
      </p>
      <ul className="list-disc ml-6 mb-4">
        <li>
          <strong>To provide and maintain our Service</strong>, including to
          monitor the usage of our Service.
        </li>
        <li>
          <strong>To manage Your Account</strong>: to manage Your registration
          as a user of the Service.
        </li>
        <li>
          <strong>For the performance of a contract</strong>: the development,
          compliance, and undertaking of the purchase contract for the products,
          items, or services You have purchased or of any other contract with Us
          through the Service.
        </li>
        <li>
          <strong>To contact You</strong>: To contact You by email, telephone
          calls, SMS, or other equivalent forms of electronic communication.
        </li>
        <li>
          <strong>To provide You with news</strong>, special offers and general
          information about other goods, services, and events.
        </li>
        <li>
          <strong>To manage Your requests</strong>: To attend and manage Your
          requests to Us.
        </li>
        <li>
          <strong>For business transfers</strong>: We may use Your information
          to evaluate or conduct a merger, divestiture, restructuring,
          reorganization, dissolution, or other sale or transfer of some or all
          of Our assets.
        </li>
        <li>
          <strong>For other purposes</strong>: We may use Your information for
          data analysis, identifying usage trends, and evaluating and improving
          our Service.
        </li>
      </ul>

      <h2 className="text-xl font-semibold mt-4">
        Retention of Your Personal Data
      </h2>
      <p className="mb-4">
        The Company will retain Your Personal Data only for as long as is
        necessary for the purposes set out in this Privacy Policy. We will
        retain and use Your Personal Data to the extent necessary to comply with
        our legal obligations.
      </p>
      <p className="mb-4">
        The Company will also retain Usage Data for internal analysis purposes.
        Usage Data is generally retained for a shorter period of time.
      </p>

      <h2 className="text-xl font-semibold mt-4">
        Transfer of Your Personal Data
      </h2>
      <p className="mb-4">
        Your information, including Personal Data, is processed at the Company's
        operating offices and in other locations where the parties involved in
        processing are located. This means Your information may be transferred
        to computers located outside of Your state, province, country, or other
        governmental jurisdiction.
      </p>
      <p className="mb-4">
        The Company will take all steps reasonably necessary to ensure that Your
        data is treated securely and in accordance with this Privacy Policy.
      </p>

      <h2 className="text-xl font-semibold mt-4">Delete Your Personal Data</h2>
      <p className="mb-4">
        You have the right to delete or request that We assist in deleting the
        Personal Data that We have collected about You.
      </p>
      <p className="mb-4">
        Our Service may give You the ability to delete certain information about
        You from within the Service.
      </p>
      <p className="mb-4">
        You may also contact Us to request access to, correct, or delete any
        personal information that You have provided to Us.
      </p>

      <h2 className="text-xl font-semibold mt-4">
        Disclosure of Your Personal Data
      </h2>
      <p className="mb-4">
        <strong>Business Transactions:</strong> If the Company is involved in a
        merger, acquisition, or asset sale, Your Personal Data may be
        transferred.
      </p>
      <p className="mb-4">
        <strong>Law enforcement:</strong> Under certain circumstances, the
        Company may be required to disclose Your Personal Data if required to do
        so by law or in response to valid requests by public authorities.
      </p>
      <p className="mb-4">
        <strong>Other legal requirements:</strong> The Company may disclose Your
        Personal Data in good faith to comply with a legal obligation, protect
        the rights or property of the Company, or prevent wrongdoing.
      </p>

      <h2 className="text-xl font-semibold mt-4">
        Security of Your Personal Data
      </h2>
      <p className="mb-4">
        The security of Your Personal Data is important to Us, but no method of
        transmission over the Internet, or method of electronic storage is 100%
        secure.
      </p>

      <h2 className="text-xl font-semibold mt-4">Children's Privacy</h2>
      <p className="mb-4">
        Our Service does not address anyone under the age of 13. We do not
        knowingly collect personally identifiable information from anyone under
        the age of 13.
      </p>

      <h2 className="text-xl font-semibold mt-4">Links to Other Websites</h2>
      <p className="mb-4">
        Our Service may contain links to other websites that are not operated by
        Us. We strongly advise You to review the Privacy Policy of every site
        You visit.
      </p>

      <h2 className="text-xl font-semibold mt-4">
        Changes to this Privacy Policy
      </h2>
      <p className="mb-4">
        We may update Our Privacy Policy from time to time. We will notify You
        of any changes by posting the new Privacy Policy on this page.
      </p>
      <p className="mb-4">
        We will let You know via email and/or a prominent notice on Our Service,
        prior to the change becoming effective.
      </p>

      <h2 className="text-xl font-semibold mt-4">Contact Us</h2>
      <p className="mb-4">
        If you have any questions about this Privacy Policy, You can contact us:
      </p>
      <ul className="list-disc ml-6 mb-4">
        <li>
          By email:{" "}
          <a href="mailto:h.m.sadman.sakib@gmail.com" className="text-blue-500">
            h.m.sadman.sakib@gmail.com
          </a>
        </li>
      </ul>
    </div>
  );
};

export default PrivacyPolicy;
